---
swagger: "2.0"
info:
  description: "This is an Itty Bitty Money server.  \n"
  version: "1.0.2"
  title: "Money Rest Client"
host: "virtserver.swaggerhub.com"
basePath: "/mmaffa/MoneyREST/1.0.2"
tags:
- name: "dataset"
  description: "Dataset Operations"
schemes:
- "https"
- "http"
paths:
  /dataset/currencySelection/{currencyName}:
    post:
      tags:
      - "dataset"
      summary: "Selects a specific currency type"
      description: "The currency type should be either bitcoin, bitconnect, dash,\
        \ ethereum, iota, litecoin, monero, nem, neo, numeraire, omisego, qtum, ripple,\
        \ stratis, or waves"
      operationId: "dataset_currency_selection_currency_name_post"
      produces:
      - "application/json"
      parameters:
      - name: "currencyName"
        in: "path"
        description: "Should be equal to either bitcoin, bitconnect, dash, ethereum,\
          \ iota, litecoin, monero, nem, neo, numeraire, omisego, qtum, ripple, stratis,\
          \ or waves"
        required: true
        type: "string"
      responses:
        200:
          description: "successfully returned json"
          schema:
            $ref: "#/definitions/ApiResponse"
      x-swagger-router-controller: "swagger_server.controllers.dataset_controller"
  /dataset/train/{currencyName}:
    post:
      tags:
      - "dataset"
      summary: "Trains based on the currency selected"
      description: "Should be either bitcoin, bitconnect, dash, ethereum, iota, litecoin,\
        \ monero, nem, neo, numeraire, omisego, qtum, ripple, stratis, or waves"
      operationId: "dataset_train_currency_name_post"
      produces:
      - "application/json"
      parameters:
      - name: "currencyName"
        in: "path"
        description: "Should be equal to either bitcoin, bitconnect, dash, ethereum,\
          \ iota, litecoin, monero, nem, neo, numeraire, omisego, qtum, ripple, stratis,\
          \ or waves"
        required: true
        type: "string"
      responses:
        200:
          description: "successfully returned json"
          schema:
            $ref: "#/definitions/ApiResponse"
      x-swagger-router-controller: "swagger_server.controllers.dataset_controller"
  /dataset/modelType/{modelType}:
    post:
      tags:
      - "dataset"
      summary: "Selects a model type"
      description: "1. Linear Regression, 2. Support Vector Regression, 3. Multilayer\
        \ Perceptron"
      operationId: "dataset_model_type_model_type_post"
      produces:
      - "application/json"
      parameters:
      - name: "modelType"
        in: "path"
        description: "Must be a number equal to 1, 2, or 3"
        required: true
        type: "integer"
      responses:
        200:
          description: "successfully returned json"
          schema:
            $ref: "#/definitions/ApiResponse"
      x-swagger-router-controller: "swagger_server.controllers.dataset_controller"
  /dataset/operationType/{operationType}:
    post:
      tags:
      - "dataset"
      summary: "Selects what operation to do, either training, testing, or prediction"
      description: "1. Train, 2. Test, 3. Predict"
      operationId: "dataset_operation_type_operation_type_post"
      produces:
      - "application/json"
      parameters:
      - name: "operationType"
        in: "path"
        description: "Must be a number equal to 1, 2, or 3"
        required: true
        type: "integer"
      responses:
        200:
          description: "successfully returned json"
          schema:
            $ref: "#/definitions/ApiResponse"
      x-swagger-router-controller: "swagger_server.controllers.dataset_controller"
  /dataset/graphSelection/{graphSelection}:
    post:
      tags:
      - "dataset"
      summary: "Selects a graph type"
      description: "1. Trend Curve, 2. Candlestick, 3. Correlation Map"
      operationId: "dataset_graph_selection_graph_selection_post"
      produces:
      - "application/json"
      parameters:
      - name: "graphSelection"
        in: "path"
        description: "Must be a number equal to 1, 2, or 3"
        required: true
        type: "integer"
      responses:
        200:
          description: "successfully returned json"
          schema:
            $ref: "#/definitions/ApiResponse"
      x-swagger-router-controller: "swagger_server.controllers.dataset_controller"
  /dataset/graphCorrelation/{correlationType}:
    post:
      tags:
      - "dataset"
      summary: "Returns a graph utilizing the selected correlation type"
      description: "1. Spearman, 2. Pearson, 3. Kendall"
      operationId: "dataset_graph_correlation_correlation_type_post"
      produces:
      - "application/json"
      parameters:
      - name: "correlationType"
        in: "path"
        description: "Must be a number equal to 1, 2, or 3"
        required: true
        type: "integer"
      responses:
        200:
          description: "successfully returned json"
          schema:
            $ref: "#/definitions/InlineImage"
      x-swagger-router-controller: "swagger_server.controllers.dataset_controller"
  /dataset/getTable/{tableName}:
    post:
      tags:
      - "dataset"
      summary: "Returns the specified table"
      description: "Returns the HTML Representation of the table."
      operationId: "dataset_get_table_table_name_post"
      produces:
      - "application/json"
      parameters:
      - name: "tableName"
        in: "path"
        description: "Should be equal to either bitcoin, bitconnect, dash, ethereum,\
          \ iota, litecoin, monero, nem, neo, numeraire, omisego, qtum, ripple, stratis,\
          \ or waves"
        required: true
        type: "string"
      responses:
        200:
          description: "successfully returned json"
          schema:
            $ref: "#/definitions/Table"
      x-swagger-router-controller: "swagger_server.controllers.dataset_controller"
  /dataset/getStats:
    get:
      tags:
      - "dataset"
      summary: "Get Statistics for the Dataset"
      description: "Returns values of count, mean, median, mode, min, max, standard\
        \ deviation (std) for the dataset"
      operationId: "dataset_get_stats_get"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Successfully returned json"
          schema:
            $ref: "#/definitions/inline_response_200"
        400:
          description: "Error 400: Unable to produce JSON"
      x-swagger-router-controller: "swagger_server.controllers.dataset_controller"
securityDefinitions:
  datasetstore_auth:
    type: "oauth2"
    authorizationUrl: "http://datasetstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:datasets: "modify datasets in your account"
      read:datasets: "read your datasets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Table:
    type: "object"
    properties:
      html:
        type: "string"
        description: "html table code"
    example:
      html: "html"
  InlineImage:
    type: "object"
    properties:
      imageText:
        type: "string"
        description: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAt0AAAHwCAYAAAB67dOHAAAABHNCSVQICAg..."
    example:
      imageText: "imageText"
    xml:
      name: "User"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
    example:
      code: 0
      type: "type"
      message: "message"
  inline_response_200:
    properties:
      count:
        type: "number"
      mean:
        type: "number"
      std:
        type: "number"
      min:
        type: "number"
      25%:
        type: "number"
      50%:
        type: "number"
      75%:
        type: "number"
      max:
        type: "number"
    example:
      std: 1.46581298050294517310021547018550336360931396484375
      25%: 5.63737665663332876420099637471139430999755859375
      min: 5.962133916683182377482808078639209270477294921875
      max: 9.301444243932575517419536481611430644989013671875
      mean: 6.02745618307040320615897144307382404804229736328125
      75%: 7.061401241503109105224211816675961017608642578125
      count: 0.80082819046101150206595775671303272247314453125
      50%: 2.3021358869347654518833223846741020679473876953125
