# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineImage(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, image_text: str=None):  # noqa: E501
        """InlineImage - a model defined in Swagger

        :param image_text: The image_text of this InlineImage.  # noqa: E501
        :type image_text: str
        """
        self.swagger_types = {
            'image_text': str
        }

        self.attribute_map = {
            'image_text': 'imageText'
        }

        self._image_text = image_text

    @classmethod
    def from_dict(cls, dikt) -> 'InlineImage':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InlineImage of this InlineImage.  # noqa: E501
        :rtype: InlineImage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def image_text(self) -> str:
        """Gets the image_text of this InlineImage.

        data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAt0AAAHwCAYAAAB67dOHAAAABHNCSVQICAg...  # noqa: E501

        :return: The image_text of this InlineImage.
        :rtype: str
        """
        return self._image_text

    @image_text.setter
    def image_text(self, image_text: str):
        """Sets the image_text of this InlineImage.

        data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAt0AAAHwCAYAAAB67dOHAAAABHNCSVQICAg...  # noqa: E501

        :param image_text: The image_text of this InlineImage.
        :type image_text: str
        """

        self._image_text = image_text
