# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Table(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, html: str=None):  # noqa: E501
        """Table - a model defined in Swagger

        :param html: The html of this Table.  # noqa: E501
        :type html: str
        """
        self.swagger_types = {
            'html': str
        }

        self.attribute_map = {
            'html': 'html'
        }

        self._html = html

    @classmethod
    def from_dict(cls, dikt) -> 'Table':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Table of this Table.  # noqa: E501
        :rtype: Table
        """
        return util.deserialize_model(dikt, cls)

    @property
    def html(self) -> str:
        """Gets the html of this Table.

        html table code  # noqa: E501

        :return: The html of this Table.
        :rtype: str
        """
        return self._html

    @html.setter
    def html(self, html: str):
        """Sets the html of this Table.

        html table code  # noqa: E501

        :param html: The html of this Table.
        :type html: str
        """

        self._html = html
